test-blog4:
  stage: test
  script:
    - cd blog4
    - bundle install
    - rails db:migrate RAILS_ENV=test

  only:
    - blog4

deploy-blog4:
  stage: deploy
  script:
    - rsync -arv ./blog4 /
    - cd /blog4
    - bundle install
    - rails db:migrate
    - sv restart blog4
  only:
  - blog4

